import argparse

from metadata.sources import NovelUpdatesSource, WebnovelDotComSource

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Extract novel metadata")
    parser.add_argument(
        "--root",
        required=True,
        help="Path to the novel root folder (folder generated by lncrawler)",
    )
    parser.add_argument(
        "--metadata-uri",
        required=True,
        help="Metadata website uri",
    )

    args = parser.parse_args()

    source = WebnovelDotComSource(args.root, args.metadata_uri)

    source.execute()